Update ServiceContainer.php
jonnnnyw/php-phantomjs pull request #235
Opened 2018-01-22 16:20 UTC by cocostru

#216 
#217 
#232

2018-01-22 19:07 UTC, lucacri commented
+1

2018-01-27 10:11 UTC, lucacri commented
Please merge this

2018-03-07 11:33 UTC, BR0kEN- requested changes

2018-03-07 11:33 UTC, BR0kEN- commented on composer.json
> +    "name": "cocostru/php-phantomjs",
You should remove this and similar modifications in order to consider merge of this PR.

2018-03-07 11:33 UTC, BR0kEN- commented on composer.json
> +            "name": "Denis Kostukovic",
Should be removed before merging to the main repository.

2018-03-23 15:32 UTC, iantearle commented
Please merge this. php-phantoms is broken without it.

2018-04-03 12:03 UTC, wcjonathan commented
I've sent a tweet to the author to see if he'll merge this.

2018-04-03 12:04 UTC, merged